title: andrearvidsson.github.io
description: Being a geek is a great thing. I think we're all geeks. Being a geek means you're passionate about something and that defines your uniqueness. I would rather be passionate about something than be apathetic about everything.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker